### ISSUE TITLE
Add Sauce

### ISSUE THREAD

**Issue by rosedoucette** [rosedoucette/Project-6-hot-sauce#2]
Hi @AccessiT3ch , I am working on testing the create sauce and I am having trouble figuring out how to diagnose the error. 
It's showing the request method as PUT, which should be correct because that's where the createSauce route is located. 
However, the error message I'm getting is a 500, which isn't located within the createSauce section, but it's found in both getAllProducts and getOneProduct. The error message says 500 Internal Server Error, which isn't a return message I have anywhere, so I'm assuming it's a generic response. I'm just not sure how to go about diagnosing and solving the issue. 

![image](https://github.com/rosedoucette/Project-6-hot-sauce/assets/117312528/903a5b94-c4fc-4bb0-b743-d911d79085d5)
![image](https://github.com/rosedoucette/Project-6-hot-sauce/assets/117312528/65189d6e-d110-48df-aa0e-593b30f4bd76)
![image](https://github.com/rosedoucette/Project-6-hot-sauce/assets/117312528/58435915-1a11-47f9-af0e-c4d36c7b14c5)

**Comment by AccessiT3ch** [comment]
@rosedoucette Correct, 500 is a generic "something broke" response, and usually when there is such an error there will be some sort of error message in the terminal that is running your backend (in VS Code). Is there anything there when you get the 500 error?

After a quick look, it does look like there are some potential things, which while valid JS, may be error prone in case the script isn't getting the request with the data it's expecting. For example, JSON.parse is a very fickle command and can fail in many ways, so we have to make sure (usually with an if statement) that what we are parsing is a string. In this case, express is doing the parsing for you, so req.body.sauce is already an object (or undefined, but is should be an object). One way to test this is by looking at your request headers to make sure the payload looks right in the network tab of your dev tools.

**Comment by rosedoucette** [comment]
I'm not seeing any errors in the vs terminal, no. 

payload is returning: 
sauce: {"name":"picante","manufacturer":"tu madre","description":"de la cocina de tu mama ","mainPepper":"chili peppers","heat":3,"userId":"64dfc97535de0702eae1d5ca"}
image: (binary)
so it looks like everything is there. 

I am getting an error in the response that reads: 
Error: ENOENT: no such file or directory, open 'C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\images\hot_sauce.jpg1692732531286.jpg'
So it looks to me like it may be an issue with the image uploading, but I could be wrong.

**Comment by AccessiT3ch** [comment]
@rosedoucette - Aha! I believe all you need to do is manually create an `images` folder!!

**Comment by rosedoucette** [comment]
Yes, I left that part out. I have a blank images folder already

**Comment by AccessiT3ch** [comment]
Multer documentation explicitly says the middleware will create the folder if it doesn't exist, but I have never seen it successfully do so and have always had to manually create the folder.

Ah I see..

**Comment by AccessiT3ch** [comment]
@rosedoucette - Are the image files being added to the image folder in your repo? 

Also, [have you removed this](https://github.com/rosedoucette/Project-6-hot-sauce/blob/main/Back/controllers/sauce.js#L12)?

`Error: ENOENT:` usually indicates a lack of connection to the server (if its crashing) or a wrong route..

**Comment by rosedoucette** [comment]
I deleted the current images folder and added a new one. It's adding images to the folder now, yes. It looks like it's working, except I have a bunch of new errors that popped up in the terminal.

**Comment by AccessiT3ch** [comment]
Aha! Screenshots of the errors?

**Comment by rosedoucette** [comment]
TypeError: (intermediate value).then is not a function
    at exports.createSauce (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\controllers\sauce.js:27:8)
    at Layer.handle [as handle_request] (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\multer\lib\make-middleware.js:49:68)
    at C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\multer\lib\make-middleware.js:155:11
    at WriteStream.<anonymous> (C:\Users\rosed\Documents\Open Classrooms\Project 6\Web-Developer-P6-master\Project-6-hot-sauce\Back\node_modules\multer\storage\disk.js:43:9)
    at WriteStream.emit (node:events:525:35)
    at finish (node:internal/streams/writable:748:10)
    at finishMaybe (node:internal/streams/writable:733:9)

**Comment by AccessiT3ch** [comment]
@rosedoucette it also looks like you can simplify these ([where you're defining the images route](https://github.com/rosedoucette/Project-6-hot-sauce/blob/main/Back/app.js#L31-L34)) lines by just using the first one

**Comment by rosedoucette** [comment]
Yup, that's weird. Not sure why that's in there twice. my bad

**Comment by AccessiT3ch** [comment]
Aaahh, ok, so we can follow this stack trace straight to the issue: `controllers\sauce.js:27:8`

**Comment by rosedoucette** [comment]
yeah it looks like it doesn't like my .then situation

**Comment by AccessiT3ch** [comment]
instead of:
```js
new Sauce({ ... }) // new Sauce() doesn't return a promise
  .then()
  .catch()
```

it should be more like:
```js
const sauce = new Sauce({ ... }) // new Sauce() returns a Sauce instance
sauce.save().then.().catch() // the sauce instance can call methods like .save() which do return promises
```

**Comment by AccessiT3ch** [comment]
@rosedoucette the "instance" that is returned when instantiate a schema (`new Sauce()`) is a MongoDB [`Document`](https://mongoosejs.com/docs/api/document.html), which has all sorts of methods available to us via the [`Document API`](https://mongoosejs.com/docs/api/document.html)!

**Comment by rosedoucette** [comment]
Ok. just trying to figure out how to type the .save, I'm not really familiar with it.

**Comment by AccessiT3ch** [comment]
There won't be anything int the .save() parenthesis, you just need to save the new Sauce as a variable and have that variable do `.save().then(....).catch(....)` :)

**Comment by rosedoucette** [comment]
ok, got it. It's working better now, enough that I was able to at least create the sauce. It looks like I'm getting the appropriate response back now
